$ cupper help

Commands:
  cupper create [PROJECT_NAME]  # Create the project s...
  cupper generate               # Extract configuratio...
  cupper help [COMMAND]         # Describe available c...
  cupper ohai                   # List Ohai plugins
